name: Docker

on:
  workflow_dispatch:
    inputs:
      upstream_branch:
        description: ''
        required: true
        default: 'dev'
      image_tag:
        description: ''
        required: true
        default: 'unstable'
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: hpoolchia
  
jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build docker image
        run: docker build --no-cache --build-arg BRANCH=${{ github.event.inputs.upstream_branch }} -t ghcr.io/vincywindy/hpoolchia:${{ github.event.inputs.image_tag }} .

      - name: Push to github packages
        run: docker push ghcr.io/vincywindy/hpoolchia:${{ github.event.inputs.image_tag }}
